UMC: UMC::TRationalType< BaseType > Class Template Reference
UMC::TRationalType< BaseType > Class Template Reference
#include <RationalType.h>
Public Member Functions
TRationalType (const BaseType &numerator, const BaseType &denominator=1)
TRationalType (const TRationalType &source)
TRationalType & operator= (const TRationalType &right)
bool operator== (const TRationalType &right) const
void Numerator (const BaseType &value)
void Denominator (const BaseType &value)
BaseType Numerator () const
BaseType Denominator () const
Protected Attributes
BaseType mNumerator
BaseType mDenominator
Detailed Description
template<typename BaseType>
class UMC::TRationalType< BaseType >
Definition at line 22 of file RationalType.h.
Constructor & Destructor Documentation
template<typename BaseType > UMC::TRationalType< BaseType >::TRationalType (const BaseType & numerator, const BaseType & denominator = 1) inline
Definition at line 24 of file RationalType.h.
                         : mNumerator( numerator )
                         , mDenominator( denominator ) { /* assert( denominator != 0 );*/ }
template<typename BaseType > UMC::TRationalType< BaseType >::TRationalType (const TRationalType< BaseType > & source) inline
Definition at line 28 of file RationalType.h.
                         : mNumerator( source.mNumerator )
                         , mDenominator( source.mDenominator ) { }
Member Function Documentation
template<typename BaseType > void UMC::TRationalType< BaseType >::Denominator (const BaseType & value) inline
Definition at line 43 of file RationalType.h.
References UMC::TRationalType< BaseType >::mDenominator.
Referenced by UMC::ConvertFromStandardFrameRate(), UMC::ConvertToStandardFrameRate(), and UMC::operator<<().
 { /* assert( denominator != 0 ); */ mDenominator = value; }
template<typename BaseType > BaseType UMC::TRationalType< BaseType >::Denominator () const inline
Definition at line 46 of file RationalType.h.
References UMC::TRationalType< BaseType >::mDenominator.
 { return mDenominator; }
template<typename BaseType > void UMC::TRationalType< BaseType >::Numerator (const BaseType & value) inline
Definition at line 42 of file RationalType.h.
References UMC::TRationalType< BaseType >::mNumerator.
Referenced by UMC::ConvertFromStandardFrameRate(), UMC::ConvertToStandardFrameRate(), and UMC::operator<<().
 { mNumerator = value; }
template<typename BaseType > BaseType UMC::TRationalType< BaseType >::Numerator () const inline
Definition at line 45 of file RationalType.h.
References UMC::TRationalType< BaseType >::mNumerator.
 { return mNumerator; }
template<typename BaseType > TRationalType& UMC::TRationalType< BaseType >::operator= (const TRationalType< BaseType > & right) inline
Definition at line 32 of file RationalType.h.
References UMC::TRationalType< BaseType >::mDenominator, and UMC::TRationalType< BaseType >::mNumerator.
{
                         mNumerator = right.mNumerator;
                         mDenominator = right.mDenominator;
                         return *this;
                 }
template<typename BaseType > bool UMC::TRationalType< BaseType >::operator== (const TRationalType< BaseType > & right) const inline
Definition at line 38 of file RationalType.h.
References UMC::TRationalType< BaseType >::mDenominator, and UMC::TRationalType< BaseType >::mNumerator.
{
                         return ( ( mNumerator * right.mDenominator ) == ( mDenominator * right.mNumerator ) );
                 }
Member Data Documentation
template<typename BaseType > BaseType UMC::TRationalType< BaseType >::mDenominator protected
Definition at line 50 of file RationalType.h.
Referenced by UMC::TRationalType< BaseType >::Denominator(), UMC::TRationalType< BaseType >::operator=(), and UMC::TRationalType< BaseType >::operator==().
template<typename BaseType > BaseType UMC::TRationalType< BaseType >::mNumerator protected
Definition at line 49 of file RationalType.h.
Referenced by UMC::TRationalType< BaseType >::Numerator(), UMC::TRationalType< BaseType >::operator=(), and UMC::TRationalType< BaseType >::operator==().
The documentation for this class was generated from the following file:
C:/Users/kuspande/Git/UMC/public/include/baseTypes/RationalType.h