UMC: UMC::TimeCode Class Reference
UMC::TimeCode Class Reference
#include <TimeCode.h>
Public Types
enum eStandardFrameRates {
k24Fps = 0, k25Fps = 1, k30Fps = 2, k50Fps = 3,
k60Fps = 4, k23_976Fps = 5, k29_97Fps = 6, k59_94Fps = 7,
kNonStandardFrameRate = Max_UMC_Int32
}
Public Member Functions
TimeCode (const FrameRate &frameRate, UMC_Uns8 hours=0, UMC_Uns8 minutes=0, UMC_Uns8 seconds=0, UMC_Uns64 frames=0, bool isDropFrame=false)
TimeCode (eStandardFrameRates standardFrameRate, UMC_Uns8 hours=0, UMC_Uns8 minutes=0, UMC_Uns8 seconds=0, UMC_Uns64 frames=0, bool isDropFrame=false)
TimeCode (const UMC::FrameRate &frameRate, const char *smpteTimeCode)
TimeCode (eStandardFrameRates standardFrameRate, const char *smpteTimeCode)
void DropFrame ()
void NonDropFrame ()
bool IsDropFrame () const
bool IsNonDropFrame () const
void FrameRate (const UMC::FrameRate &frameRate)
UMC::FrameRate FrameRate () const
void StandardFrameRate (eStandardFrameRates standardFrameRate)
eStandardFrameRates StandardFrameRate () const
void Hours (const UMC_Uns8 &hours)
UMC_Uns8 Hours () const
void Minutes (const UMC_Uns8 &minutes)
UMC_Uns8 Minutes () const
void Seconds (const UMC_Uns8 &seconds)
UMC_Uns8 Seconds () const
void Frames (const UMC_Uns64 &frames)
UMC_Uns64 Frames () const
void SMPTETimecode (const char *smpteTimeCode)
std::string SMPTETimecode () const
bool operator== (const TimeCode &right) const
Protected Attributes
UMC::FrameRate mFrameRate
bool mIsDropFrame
UMC_Uns8 mHours
UMC_Uns8 mMinutes
UMC_Uns8 mSeconds
UMC_Uns64 mFrames
eStandardFrameRates mStandardFrameRate
Detailed Description
Definition at line 22 of file TimeCode.h.
Member Enumeration Documentation
enum UMC::TimeCode::eStandardFrameRates
Enumerator
k24Fps
k25Fps
k30Fps
k50Fps
k60Fps
k23_976Fps
k29_97Fps
k59_94Fps
kNonStandardFrameRate
Definition at line 24 of file TimeCode.h.
{
                         k24Fps                  = 0,
                         k25Fps                  = 1,
                         k30Fps                  = 2,
                         k50Fps                  = 3,
                         k60Fps                  = 4,
                         k23_976Fps              = 5,
                         k29_97Fps               = 6,
                         k59_94Fps               = 7,
                         kNonStandardFrameRate = Max_UMC_Int32
                 } eStandardFrameRates;
Constructor & Destructor Documentation
UMC::TimeCode::TimeCode (const FrameRate & frameRate, UMC_Uns8 hours = 0, UMC_Uns8 minutes = 0, UMC_Uns8 seconds = 0, UMC_Uns64 frames = 0, bool isDropFrame = false)
Definition at line 171 of file TimeCode.cpp.
                 : mFrameRate( frameRate )
                 , mHours( hours )
                 , mMinutes( minutes )
                 , mSeconds( seconds )
                 , mFrames( frames )
                 , mIsDropFrame( isDropFrame )
                 , mStandardFrameRate( ConvertToStandardFrameRate( frameRate ) )
         {
                 /*assert( frames < frameRate.Numerator() / frameRate.Denominator() );
                                 assert( seconds < 59 );
                                 assert( minutes < 59 );
                                 assert( hours < 23 );*/
         }
UMC::TimeCode::TimeCode (eStandardFrameRates standardFrameRate, UMC_Uns8 hours = 0, UMC_Uns8 minutes = 0, UMC_Uns8 seconds = 0, UMC_Uns64 frames = 0, bool isDropFrame = false)
Definition at line 187 of file TimeCode.cpp.
                 : mFrameRate( ConvertFromStandardFrameRate( standardFrameRate ) )
                 , mHours( hours )
                 , mMinutes( minutes )
                 , mSeconds( seconds )
                 , mFrames( frames )
                 , mIsDropFrame( isDropFrame )
                 , mStandardFrameRate( standardFrameRate )
         {
                 /*assert( frames < mFrameRate.Numerator() / mFrameRate.Denominator() );
                 assert( seconds < 59 );
                 assert( minutes < 59 );
                 assert( hours < 23 );*/
         }
UMC::TimeCode::TimeCode (const UMC::FrameRate & frameRate, const char * smpteTimeCode)
Definition at line 147 of file TimeCode.cpp.
References UMC::ParseSMPTETimeCode().
                 : mFrameRate( frameRate )
                 , mIsDropFrame( false )
                 , mHours( 0 )
                 , mMinutes( 0 )
                 , mSeconds( 0 )
                 , mFrames( 0 )
                 , mStandardFrameRate( ConvertToStandardFrameRate( frameRate ) )
         {
                 ParseSMPTETimeCode( smpteTimeCode, *this );
         }
UMC::TimeCode::TimeCode (eStandardFrameRates standardFrameRate, const char * smpteTimeCode)
Definition at line 159 of file TimeCode.cpp.
References UMC::ParseSMPTETimeCode().
                 : mFrameRate( ConvertFromStandardFrameRate( standardFrameRate ) )
                 , mIsDropFrame( false )
                 , mHours( 0 )
                 , mMinutes( 0 )
                 , mSeconds( 0 )
                 , mFrames( 0 )
                 , mStandardFrameRate( standardFrameRate )
         {
                 ParseSMPTETimeCode( smpteTimeCode, *this );
         }
Member Function Documentation
void UMC::TimeCode::DropFrame () inline
Definition at line 47 of file TimeCode.h.
References mIsDropFrame.
Referenced by UMC::ParseSMPTETimeCode().
 { mIsDropFrame = true; }
void UMC::TimeCode::FrameRate (const UMC::FrameRate & frameRate)
Definition at line 226 of file TimeCode.cpp.
References UMC::ConvertToStandardFrameRate(), mFrameRate, and mStandardFrameRate.
{
                 mFrameRate = frameRate;
                 mStandardFrameRate = ConvertToStandardFrameRate( frameRate );
                 /*assert( mFrames < mFrameRate.Numerator() / mFrameRate.Denominator() ); */
         }
UMC::FrameRate UMC::TimeCode::FrameRate () const inline
Definition at line 53 of file TimeCode.h.
References mFrameRate.
 { return mFrameRate; }
void UMC::TimeCode::Frames (const UMC_Uns64 & frames) inline
Definition at line 67 of file TimeCode.h.
References mFrames.
Referenced by UMC::ParseSMPTETimeCode().
 { /*assert( mFrames < mFrameRate.Numerator() / mFrameRate.Denominator() );*/ mFrames = frames; }
UMC_Uns64 UMC::TimeCode::Frames () const inline
Definition at line 68 of file TimeCode.h.
References mFrames.
 { return mFrames; }
void UMC::TimeCode::Hours (const UMC_Uns8 & hours) inline
Definition at line 58 of file TimeCode.h.
References mHours.
Referenced by UMC::ParseSMPTETimeCode().
 { /*assert( hours < 24 );*/ mHours = hours; }
UMC_Uns8 UMC::TimeCode::Hours () const inline
Definition at line 59 of file TimeCode.h.
References mHours.
 { return mHours; }
bool UMC::TimeCode::IsDropFrame () const inline
Definition at line 49 of file TimeCode.h.
References mIsDropFrame.
 { return mIsDropFrame; }
bool UMC::TimeCode::IsNonDropFrame () const inline
Definition at line 50 of file TimeCode.h.
References mIsDropFrame.
Referenced by UMC::ParseSMPTETimeCode().
 { return !mIsDropFrame; }
void UMC::TimeCode::Minutes (const UMC_Uns8 & minutes) inline
Definition at line 61 of file TimeCode.h.
References mMinutes.
Referenced by UMC::ParseSMPTETimeCode().
 { /*assert( minutes < 60);*/ mMinutes = minutes; }
UMC_Uns8 UMC::TimeCode::Minutes () const inline
Definition at line 62 of file TimeCode.h.
References mMinutes.
 { return mMinutes; }
void UMC::TimeCode::NonDropFrame () inline
Definition at line 48 of file TimeCode.h.
References mIsDropFrame.
 { mIsDropFrame = false; }
bool UMC::TimeCode::operator== (const TimeCode & right) const inline
Definition at line 74 of file TimeCode.h.
References mFrameRate, mFrames, mHours, mIsDropFrame, mMinutes, mSeconds, and mStandardFrameRate.
{
                         return ( mFrameRate == right.mFrameRate &&
                                 mIsDropFrame == right.mIsDropFrame &&
                                 mHours == right.mHours &&
                                 mMinutes == right.mMinutes &&
                                 mSeconds == right.mSeconds &&
                                 mFrames == right.mFrames &&
                                 mStandardFrameRate == right.mStandardFrameRate
                                 );
                 }
void UMC::TimeCode::Seconds (const UMC_Uns8 & seconds) inline
Definition at line 64 of file TimeCode.h.
References mSeconds.
Referenced by UMC::ParseSMPTETimeCode().
 { /*assert( seconds < 60 );*/ mSeconds = seconds; }
UMC_Uns8 UMC::TimeCode::Seconds () const inline
Definition at line 65 of file TimeCode.h.
References mSeconds.
 { return mSeconds; }
void UMC::TimeCode::SMPTETimecode (const char * smpteTimeCode)
Definition at line 222 of file TimeCode.cpp.
References UMC::ParseSMPTETimeCode().
Referenced by UMC::operator<<().
{
                 ParseSMPTETimeCode( smpteTimeCode, *this );
         }
std::string UMC::TimeCode::SMPTETimecode () const
Definition at line 204 of file TimeCode.cpp.
References mFrames, mHours, mIsDropFrame, mMinutes, and mSeconds.
{
                 char seperator = ':';
                 if ( mIsDropFrame )
                         seperator = ';';
                 std::stringstream buf;
                 buf<<std::right<<std::setfill('0')<<std::setw(2)<<(UMC_Uns64) mHours;
                 buf<<seperator;
                 buf << std::right << std::setfill( '0' ) << std::setw( 2 ) <<(UMC_Uns64) mMinutes;
                 buf << seperator;
                 buf << std::right << std::setfill( '0' ) << std::setw( 2 ) <<(UMC_Uns64) mSeconds;
                 buf << seperator;
                 buf << std::right << std::setfill( '0' ) << std::setw( 2 ) << mFrames;
                 return buf.str();
         }
void UMC::TimeCode::StandardFrameRate (eStandardFrameRates standardFrameRate)
Definition at line 232 of file TimeCode.cpp.
References UMC::ConvertFromStandardFrameRate(), mFrameRate, and mStandardFrameRate.
{
                 mStandardFrameRate = standardFrameRate;
                 mFrameRate = ConvertFromStandardFrameRate( standardFrameRate );
         }
eStandardFrameRates UMC::TimeCode::StandardFrameRate () const inline
Definition at line 56 of file TimeCode.h.
References mStandardFrameRate.
 { return mStandardFrameRate; }
Member Data Documentation
UMC::FrameRate UMC::TimeCode::mFrameRate protected
Definition at line 86 of file TimeCode.h.
Referenced by FrameRate(), operator==(), and StandardFrameRate().
UMC_Uns64 UMC::TimeCode::mFrames protected
Definition at line 91 of file TimeCode.h.
Referenced by Frames(), operator==(), and SMPTETimecode().
UMC_Uns8 UMC::TimeCode::mHours protected
Definition at line 88 of file TimeCode.h.
Referenced by Hours(), operator==(), and SMPTETimecode().
bool UMC::TimeCode::mIsDropFrame protected
Definition at line 87 of file TimeCode.h.
Referenced by DropFrame(), IsDropFrame(), IsNonDropFrame(), NonDropFrame(), operator==(), and SMPTETimecode().
UMC_Uns8 UMC::TimeCode::mMinutes protected
Definition at line 89 of file TimeCode.h.
Referenced by Minutes(), operator==(), and SMPTETimecode().
UMC_Uns8 UMC::TimeCode::mSeconds protected
Definition at line 90 of file TimeCode.h.
Referenced by operator==(), Seconds(), and SMPTETimecode().
eStandardFrameRates UMC::TimeCode::mStandardFrameRate protected
Definition at line 92 of file TimeCode.h.
Referenced by FrameRate(), operator==(), and StandardFrameRate().
The documentation for this class was generated from the following files:
C:/Users/kuspande/Git/UMC/public/include/baseTypes/TimeCode.h
C:/Users/kuspande/Git/UMC/public/source/TimeCode.cpp