UMC: UMC Namespace Reference
UMC Namespace Reference
Classes
class IAudioSource
This interface represents Audio Source of UMC.
class IAudioTrack
This interface represents Audio Track added to an output.
class IClipShot
This interface is for clip shots added to tracks in UMC.
class ICustomData
This interface represents CustomData of UMC.
class ICustomDataHandler
This interface allows client to create custom extension handler.
class IFrame
This interface is for frames added to shots in UMC.
class IImageSource
This interface represents Image Source of UMC.
class IOutput
This interface acts as a base interface to all types of outputs of UMC.
class IShot
This interface acts as a base interface for shots added to tracks in UMC.
class IShotSource
This interface is for shot sources added to shots in UMC.
class ISource
This interface acts as a base interface to all types of sources of UMC.
class ITrack
This interface acts as a base interface for tracks added to outputs in UMC.
class ITransitionShot
This interface is for transition shots added to tracks in UMC.
class IUMC
This interface is used for getting, adding and removing various sources and outputs from UMC.
class IUMCNode
This interface acts as a base interface for all types of nodes in UMC.
class IUniqueIDGenerator
This interface is used for generating unique ID for the node.
class IVideoFrameSource
This interface represents VideoFrame Source of UMC.
class IVideoSource
This interface represents Video Source of UMC.
class IVideoTrack
This interface represents Video Track added to an output.
class TimeCode
class TRationalType
Typedefs
typedef TRationalType< UMC_Uns64 > Unsigned64RationalType
typedef TRationalType< UMC_Int64 > Signed64RationalType
typedef Unsigned64RationalType EditRate
typedef Unsigned64RationalType FrameRate
typedef Unsigned64RationalType AspectRatio
typedef UMC_Int64 EditUnitInCount
typedef UMC_Uns64 EditUnitDuration
typedef IUniqueIDGenerator * pIUniqueIDGenerator
typedef const IUniqueIDGenerator * pcIUniqueIDGenerator
typedef shared_ptr< IUniqueIDGenerator > spIUniqueIDGenerator
typedef shared_ptr< const IUniqueIDGenerator > spcIUniqueIDGenerator
typedef IUMCNode * pIUMCNode
typedef const IUMCNode * pcIUMCNode
typedef shared_ptr< IUMCNode > spIUMCNode
typedef shared_ptr< const IUMCNode > spcIUMCNode
typedef weak_ptr< IUMCNode > wpIUMCNode
typedef weak_ptr< const IUMCNode > wpcIUMCNode
typedef ISource * pISource
typedef const ISource * pcISource
typedef shared_ptr< ISource > spISource
typedef shared_ptr< const ISource > spcISource
typedef IVideoSource * pIVideoSource
typedef const IVideoSource * pcIVideoSource
typedef shared_ptr< IVideoSource > spIVideoSource
typedef shared_ptr< const IVideoSource > spcIVideoSource
typedef IAudioSource * pIAudioSource
typedef const IAudioSource * pcIAudioSource
typedef shared_ptr< IAudioSource > spIAudioSource
typedef shared_ptr< const IAudioSource > spcIAudioSource
typedef IVideoFrameSource * pIVideoFrameSource
typedef const IVideoFrameSource * pcIVideoFrameSource
typedef shared_ptr< IVideoFrameSource > spIVideoFrameSource
typedef shared_ptr< const IVideoFrameSource > spcIVideoFrameSource
typedef IImageSource * pIImageSource
typedef const IImageSource * pcIImageSource
typedef shared_ptr< IImageSource > spIImageSource
typedef shared_ptr< const IImageSource > spcIImageSource
typedef IUMC * pIUMC
typedef const IUMC * pcIUMC
typedef shared_ptr< IUMC > spIUMC
typedef shared_ptr< const IUMC > spcIUMC
typedef IOutput * pIOutput
typedef const IOutput * pcIOutput
typedef shared_ptr< IOutput > spIOutput
typedef shared_ptr< const IOutput > spcIOutput
typedef ITrack * pITrack
typedef const ITrack * pcITrack
typedef shared_ptr< ITrack > spITrack
typedef shared_ptr< const ITrack > spcITrack
typedef IVideoTrack * pIVideoTrack
typedef const IVideoTrack * pcIVideoTrack
typedef shared_ptr< IVideoTrack > spIVideoTrack
typedef shared_ptr< const IVideoTrack > spcIVideoTrack
typedef IAudioTrack * pIAudioTrack
typedef const IAudioTrack * pcIAudioTrack
typedef shared_ptr< IAudioTrack > spIAudioTrack
typedef shared_ptr< const IAudioTrack > spcIAudioTrack
typedef IShot * pIShot
typedef const IShot * pcIShot
typedef shared_ptr< IShot > spIShot
typedef shared_ptr< const IShot > spcIShot
typedef IClipShot * pIClipShot
typedef const IClipShot * pcIClipShot
typedef shared_ptr< IClipShot > spIClipShot
typedef shared_ptr< const IClipShot > spcIClipShot
typedef ITransitionShot * pITransitionShot
typedef const ITransitionShot * pcITransitionShot
typedef shared_ptr< ITransitionShot > spITransitionShot
typedef shared_ptr< const ITransitionShot > spcITransitionShot
typedef IFrame * pIFrame
typedef const IFrame * pcIFrame
typedef shared_ptr< IFrame > spIFrame
typedef shared_ptr< const IFrame > spcIFrame
typedef IShotSource * pIShotSource
typedef const IShotSource * pcIShotSource
typedef shared_ptr< IShotSource > spIShotSource
typedef shared_ptr< const IShotSource > spcIShotSource
typedef ICustomData * pICustomData
typedef const ICustomData * pcICustomData
typedef shared_ptr< ICustomData > spICustomData
typedef shared_ptr< const ICustomData > spcICustomData
typedef ICustomDataHandler * pICustomDataHandler
typedef const ICustomDataHandler * pcICustomDataHandler
typedef shared_ptr< ICustomDataHandler > spICustomDataHandler
typedef shared_ptr< const ICustomDataHandler > spcICustomDataHandler
Functions
std::ostream & operator<< (std::ostream &os, const Unsigned64RationalType &rt)
std::ostream & operator<< (std::ostream &os, const TimeCode &tc)
template<typename requiredNodeType >
shared_ptr< requiredNodeType > ConvertNode (const spIUMCNode &node)
static void ParseSMPTETimeCode (const char *smpteTimeCode, TimeCode &timeCode)
static TimeCode::eStandardFrameRates ConvertToStandardFrameRate (const FrameRate &frameRate)
FrameRate ConvertFromStandardFrameRate (TimeCode::eStandardFrameRates standardFrameRate)
Variables
static const UMC_Uns8 Min_UMC_Uns8 = ((UMC_Uns8) 0x00)
static const UMC_Uns8 Max_UMC_Uns8 = ((UMC_Uns8) 0xFF)
static const UMC_Uns16 Min_UMC_Uns16 = ((UMC_Uns16) 0x00)
static const UMC_Uns16 Max_UMC_Uns16 = ((UMC_Uns16) 0xFFFF)
static const UMC_Uns32 Min_UMC_Uns32 = ((UMC_Uns32) 0x00)
static const UMC_Uns32 Max_UMC_Uns32 = ((UMC_Uns32) 0xFFFFFFFF)
static const UMC_Uns64 Min_UMC_Uns64 = ((UMC_Uns64) 0x00)
static const UMC_Uns64 Max_UMC_Uns64 = ((UMC_Uns64) 0xFFFFFFFFFFFFFFFFLL)
static const UMC_Int8 Min_UMC_Int8 = ((UMC_Int8) 0x80)
static const UMC_Int8 Max_UMC_Int8 = ((UMC_Int8) 0x7F)
static const UMC_Int16 Min_UMC_Int16 = ((UMC_Int16) 0x8000)
static const UMC_Int16 Max_UMC_Int16 = ((UMC_Int16) 0x7FFF)
static const UMC_Int32 Min_UMC_Int32 = ((UMC_Int32) 0x80000000)
static const UMC_Int32 Max_UMC_Int32 = ((UMC_Int32) 0x7FFFFFFF)
static const UMC_Int64 Min_UMC_Int64 = ((UMC_Int64) 0x8000000000000000LL)
static const UMC_Int64 Max_UMC_Int64 = ((UMC_Int64) 0x7FFFFFFFFFFFFFFFLL)
static const EditUnitInCount kEditUnitInCountFromBeginning = 0
static const EditUnitDuration kEditUnitDurationTillEnd = Max_UMC_Uns64
static const size_t npos = std::string::npos
const std::string kEmptyString
Typedef Documentation
typedef Unsigned64RationalType UMC::AspectRatio
Definition at line 58 of file RationalType.h.
typedef Unsigned64RationalType UMC::EditRate
Definition at line 56 of file RationalType.h.
typedef UMC_Uns64 UMC::EditUnitDuration
Definition at line 101 of file UMCDefines.h.
typedef UMC_Int64 UMC::EditUnitInCount
Definition at line 100 of file UMCDefines.h.
typedef Unsigned64RationalType UMC::FrameRate
Definition at line 57 of file RationalType.h.
typedef const IAudioSource* UMC::pcIAudioSource
Definition at line 58 of file UMCFwdDeclarations.h.
typedef const IAudioTrack* UMC::pcIAudioTrack
Definition at line 107 of file UMCFwdDeclarations.h.
typedef const IClipShot* UMC::pcIClipShot
Definition at line 121 of file UMCFwdDeclarations.h.
typedef const ICustomData* UMC::pcICustomData
Definition at line 150 of file UMCFwdDeclarations.h.
typedef const ICustomDataHandler* UMC::pcICustomDataHandler
Definition at line 157 of file UMCFwdDeclarations.h.
typedef const IFrame* UMC::pcIFrame
Definition at line 135 of file UMCFwdDeclarations.h.
typedef const IImageSource* UMC::pcIImageSource
Definition at line 72 of file UMCFwdDeclarations.h.
typedef const IOutput* UMC::pcIOutput
Definition at line 86 of file UMCFwdDeclarations.h.
typedef const IShot* UMC::pcIShot
Definition at line 114 of file UMCFwdDeclarations.h.
typedef const IShotSource* UMC::pcIShotSource
Definition at line 142 of file UMCFwdDeclarations.h.
typedef const ISource* UMC::pcISource
Definition at line 44 of file UMCFwdDeclarations.h.
typedef const ITrack* UMC::pcITrack
Definition at line 93 of file UMCFwdDeclarations.h.
typedef const ITransitionShot* UMC::pcITransitionShot
Definition at line 128 of file UMCFwdDeclarations.h.
typedef const IUMC* UMC::pcIUMC
Definition at line 79 of file UMCFwdDeclarations.h.
typedef const IUMCNode* UMC::pcIUMCNode
Definition at line 34 of file UMCFwdDeclarations.h.
typedef const IUniqueIDGenerator* UMC::pcIUniqueIDGenerator
Definition at line 27 of file UMCFwdDeclarations.h.
typedef const IVideoFrameSource* UMC::pcIVideoFrameSource
Definition at line 65 of file UMCFwdDeclarations.h.
typedef const IVideoSource* UMC::pcIVideoSource
Definition at line 51 of file UMCFwdDeclarations.h.
typedef const IVideoTrack* UMC::pcIVideoTrack
Definition at line 100 of file UMCFwdDeclarations.h.
typedef IAudioSource* UMC::pIAudioSource
Definition at line 56 of file UMCFwdDeclarations.h.
typedef IAudioTrack* UMC::pIAudioTrack
Definition at line 105 of file UMCFwdDeclarations.h.
typedef IClipShot* UMC::pIClipShot
Definition at line 119 of file UMCFwdDeclarations.h.
typedef ICustomData* UMC::pICustomData
Definition at line 148 of file UMCFwdDeclarations.h.
typedef ICustomDataHandler* UMC::pICustomDataHandler
Definition at line 155 of file UMCFwdDeclarations.h.
typedef IFrame* UMC::pIFrame
Definition at line 133 of file UMCFwdDeclarations.h.
typedef IImageSource* UMC::pIImageSource
Definition at line 70 of file UMCFwdDeclarations.h.
typedef IOutput* UMC::pIOutput
Definition at line 84 of file UMCFwdDeclarations.h.
typedef IShot* UMC::pIShot
Definition at line 112 of file UMCFwdDeclarations.h.
typedef IShotSource* UMC::pIShotSource
Definition at line 140 of file UMCFwdDeclarations.h.
typedef ISource* UMC::pISource
Definition at line 42 of file UMCFwdDeclarations.h.
typedef ITrack* UMC::pITrack
Definition at line 91 of file UMCFwdDeclarations.h.
typedef ITransitionShot* UMC::pITransitionShot
Definition at line 126 of file UMCFwdDeclarations.h.
typedef IUMC* UMC::pIUMC
Definition at line 77 of file UMCFwdDeclarations.h.
typedef IUMCNode* UMC::pIUMCNode
Definition at line 32 of file UMCFwdDeclarations.h.
typedef IUniqueIDGenerator* UMC::pIUniqueIDGenerator
Definition at line 25 of file UMCFwdDeclarations.h.
typedef IVideoFrameSource* UMC::pIVideoFrameSource
Definition at line 63 of file UMCFwdDeclarations.h.
typedef IVideoSource* UMC::pIVideoSource
Definition at line 49 of file UMCFwdDeclarations.h.
typedef IVideoTrack* UMC::pIVideoTrack
Definition at line 98 of file UMCFwdDeclarations.h.
typedef TRationalType< UMC_Int64 > UMC::Signed64RationalType
Definition at line 54 of file RationalType.h.
typedef shared_ptr< const IAudioSource > UMC::spcIAudioSource
Definition at line 60 of file UMCFwdDeclarations.h.
typedef shared_ptr< const IAudioTrack > UMC::spcIAudioTrack
Definition at line 109 of file UMCFwdDeclarations.h.
typedef shared_ptr< const IClipShot > UMC::spcIClipShot
Definition at line 123 of file UMCFwdDeclarations.h.
typedef shared_ptr< const ICustomData > UMC::spcICustomData
Definition at line 152 of file UMCFwdDeclarations.h.
typedef shared_ptr< const ICustomDataHandler > UMC::spcICustomDataHandler
Definition at line 159 of file UMCFwdDeclarations.h.
typedef shared_ptr< const IFrame > UMC::spcIFrame
Definition at line 137 of file UMCFwdDeclarations.h.
typedef shared_ptr< const IImageSource > UMC::spcIImageSource
Definition at line 74 of file UMCFwdDeclarations.h.
typedef shared_ptr< const IOutput > UMC::spcIOutput
Definition at line 88 of file UMCFwdDeclarations.h.
typedef shared_ptr< const IShot > UMC::spcIShot
Definition at line 116 of file UMCFwdDeclarations.h.
typedef shared_ptr< const IShotSource > UMC::spcIShotSource
Definition at line 144 of file UMCFwdDeclarations.h.
typedef shared_ptr< const ISource > UMC::spcISource
Definition at line 46 of file UMCFwdDeclarations.h.
typedef shared_ptr< const ITrack > UMC::spcITrack
Definition at line 95 of file UMCFwdDeclarations.h.
typedef shared_ptr< const ITransitionShot > UMC::spcITransitionShot
Definition at line 130 of file UMCFwdDeclarations.h.
typedef shared_ptr< const IUMC > UMC::spcIUMC
Definition at line 81 of file UMCFwdDeclarations.h.
typedef shared_ptr< const IUMCNode > UMC::spcIUMCNode
Definition at line 36 of file UMCFwdDeclarations.h.
typedef shared_ptr< const IUniqueIDGenerator > UMC::spcIUniqueIDGenerator
Definition at line 29 of file UMCFwdDeclarations.h.
typedef shared_ptr< const IVideoFrameSource > UMC::spcIVideoFrameSource
Definition at line 67 of file UMCFwdDeclarations.h.
typedef shared_ptr< const IVideoSource > UMC::spcIVideoSource
Definition at line 53 of file UMCFwdDeclarations.h.
typedef shared_ptr< const IVideoTrack > UMC::spcIVideoTrack
Definition at line 102 of file UMCFwdDeclarations.h.
typedef shared_ptr< IAudioSource > UMC::spIAudioSource
Definition at line 59 of file UMCFwdDeclarations.h.
typedef shared_ptr< IAudioTrack > UMC::spIAudioTrack
Definition at line 108 of file UMCFwdDeclarations.h.
typedef shared_ptr< IClipShot > UMC::spIClipShot
Definition at line 122 of file UMCFwdDeclarations.h.
typedef shared_ptr< ICustomData > UMC::spICustomData
Definition at line 151 of file UMCFwdDeclarations.h.
typedef shared_ptr< ICustomDataHandler > UMC::spICustomDataHandler
Definition at line 158 of file UMCFwdDeclarations.h.
typedef shared_ptr< IFrame > UMC::spIFrame
Definition at line 136 of file UMCFwdDeclarations.h.
typedef shared_ptr< IImageSource > UMC::spIImageSource
Definition at line 73 of file UMCFwdDeclarations.h.
typedef shared_ptr< IOutput > UMC::spIOutput
Definition at line 87 of file UMCFwdDeclarations.h.
typedef shared_ptr< IShot > UMC::spIShot
Definition at line 115 of file UMCFwdDeclarations.h.
typedef shared_ptr< IShotSource > UMC::spIShotSource
Definition at line 143 of file UMCFwdDeclarations.h.
typedef shared_ptr< ISource > UMC::spISource
Definition at line 45 of file UMCFwdDeclarations.h.
typedef shared_ptr< ITrack > UMC::spITrack
Definition at line 94 of file UMCFwdDeclarations.h.
typedef shared_ptr< ITransitionShot > UMC::spITransitionShot
Definition at line 129 of file UMCFwdDeclarations.h.
typedef shared_ptr< IUMC > UMC::spIUMC
Definition at line 80 of file UMCFwdDeclarations.h.
typedef shared_ptr< IUMCNode > UMC::spIUMCNode
Definition at line 35 of file UMCFwdDeclarations.h.
typedef shared_ptr< IUniqueIDGenerator > UMC::spIUniqueIDGenerator
Definition at line 28 of file UMCFwdDeclarations.h.
typedef shared_ptr< IVideoFrameSource > UMC::spIVideoFrameSource
Definition at line 66 of file UMCFwdDeclarations.h.
typedef shared_ptr< IVideoSource > UMC::spIVideoSource
Definition at line 52 of file UMCFwdDeclarations.h.
typedef shared_ptr< IVideoTrack > UMC::spIVideoTrack
Definition at line 101 of file UMCFwdDeclarations.h.
typedef TRationalType< UMC_Uns64 > UMC::Unsigned64RationalType
Definition at line 53 of file RationalType.h.
typedef weak_ptr< const IUMCNode > UMC::wpcIUMCNode
Definition at line 38 of file UMCFwdDeclarations.h.
typedef weak_ptr< IUMCNode > UMC::wpIUMCNode
Definition at line 37 of file UMCFwdDeclarations.h.
Function Documentation
FrameRate UMC::ConvertFromStandardFrameRate (TimeCode::eStandardFrameRates standardFrameRate)
Definition at line 105 of file TimeCode.cpp.
References UMC::TRationalType< BaseType >::Denominator(), UMC::TimeCode::k23_976Fps, UMC::TimeCode::k24Fps, UMC::TimeCode::k25Fps, UMC::TimeCode::k29_97Fps, UMC::TimeCode::k30Fps, UMC::TimeCode::k50Fps, UMC::TimeCode::k59_94Fps, UMC::TimeCode::k60Fps, and UMC::TRationalType< BaseType >::Numerator().
Referenced by UMC::TimeCode::StandardFrameRate().
{
                 FrameRate frameRate( 1 );
                 switch ( standardFrameRate ) {
                         case TimeCode::k24Fps:
                                 frameRate.Numerator( 24 );
                                 break;
                         case TimeCode::k25Fps:
                                 frameRate.Numerator( 25 );
                                 break;
                         case TimeCode::k30Fps:
                                 frameRate.Numerator( 30 );
                                 break;
                         case TimeCode::k50Fps:
                                 frameRate.Numerator( 50 );
                                 break;
                         case TimeCode::k60Fps:
                                 frameRate.Numerator( 60 );
                                 break;
                         case TimeCode::k23_976Fps:
                                 frameRate.Numerator( 24000 );
                                 frameRate.Denominator( 1001 );
                                 break;
                         case TimeCode::k29_97Fps:
                                 frameRate.Numerator( 30000 );
                                 frameRate.Denominator( 1001 );
                                 break;
                         case TimeCode::k59_94Fps:
                                 frameRate.Numerator( 60000 );
                                 frameRate.Denominator( 1001 );
                                 break;
                 }
                 return frameRate;
         }
template<typename requiredNodeType > shared_ptr< requiredNodeType > UMC::ConvertNode (const spIUMCNode & node)
Definition at line 275 of file IUMCNode.h.
{
                 auto t = dynamic_pointer_cast< requiredNodeType >( node );
                 if ( t ) {
                         return t;
                 } else {
                         throw std::bad_cast();
                 }
         }
static TimeCode::eStandardFrameRates UMC::ConvertToStandardFrameRate (const FrameRate & frameRate) static
Definition at line 57 of file TimeCode.cpp.
References UMC::TRationalType< BaseType >::Denominator(), UMC::TimeCode::k23_976Fps, UMC::TimeCode::k24Fps, UMC::TimeCode::k25Fps, UMC::TimeCode::k29_97Fps, UMC::TimeCode::k30Fps, UMC::TimeCode::k50Fps, UMC::TimeCode::k59_94Fps, UMC::TimeCode::k60Fps, UMC::TimeCode::kNonStandardFrameRate, and UMC::TRationalType< BaseType >::Numerator().
Referenced by UMC::TimeCode::FrameRate().
{
                 UMC_Uns64 intFrameRate = frameRate.Numerator() / frameRate.Denominator();
                 bool exactMatch = intFrameRate * frameRate.Denominator() == frameRate.Numerator();
                 if ( exactMatch ) {
                         switch ( intFrameRate ) {
                                 case 24:
                                         return TimeCode::k24Fps;
                                         break;
                                 case 25:
                                         return TimeCode::k25Fps;
                                         break;
                                 case 30:
                                         return TimeCode::k30Fps;
                                         break;
                                 case 50:
                                         return TimeCode::k50Fps;
                                         break;
                                 case 60:
                                         return TimeCode::k60Fps;
                                         break;
                         }
                 }
                 double dblFrameRate = static_cast< double >( frameRate.Numerator() );
                 dblFrameRate /= frameRate.Denominator();
                 if ( dblFrameRate > 23.975 && dblFrameRate < 23.977 ) {
                         if ( frameRate.Numerator() % 24000 == 0 && frameRate.Denominator() % 1001 == 0 &&
                                 frameRate.Numerator() / 24000 == frameRate.Denominator() / 1001 )
                                 return TimeCode::k23_976Fps;
                 } else if ( dblFrameRate > 29.96 && dblFrameRate < 29.98 ) {
                         if ( frameRate.Numerator() % 30000 == 0 && frameRate.Denominator() % 1001 == 0 &&
                                 frameRate.Numerator() / 30000 == frameRate.Denominator() / 1001 )
                                 return TimeCode::k29_97Fps;
                 } else if ( dblFrameRate > 59.93 && dblFrameRate < 59.95 ) {
                         if ( frameRate.Numerator() % 60000 == 0 && frameRate.Denominator() % 1001 == 0 &&
                                 frameRate.Numerator() / 60000 == frameRate.Denominator() / 1001 )
                                 return TimeCode::k59_94Fps;
                 }
                 return TimeCode::kNonStandardFrameRate;
         }
std::ostream& UMC::operator<< (std::ostream & os, const Unsigned64RationalType & rt) inline
Definition at line 60 of file RationalType.h.
References UMC::TRationalType< BaseType >::Denominator(), and UMC::TRationalType< BaseType >::Numerator().
         {
                 os << rt.Numerator() << '/' << rt.Denominator();
                 return os;
         }
std::ostream& UMC::operator<< (std::ostream & os, const TimeCode & tc) inline
Definition at line 96 of file TimeCode.h.
References UMC::TimeCode::SMPTETimecode().
         {
                 os << tc.SMPTETimecode();
                 return os;
         }
static void UMC::ParseSMPTETimeCode (const char * smpteTimeCode, TimeCode & timeCode) static
Definition at line 22 of file TimeCode.cpp.
References UMC::TimeCode::DropFrame(), UMC::TimeCode::Frames(), UMC::TimeCode::Hours(), UMC::TimeCode::IsNonDropFrame(), UMC::TimeCode::Minutes(), npos, and UMC::TimeCode::Seconds().
Referenced by UMC::TimeCode::SMPTETimecode(), and UMC::TimeCode::TimeCode().
{
                 if ( smpteTimeCode ) {
                         std::string str( smpteTimeCode );
                         char seperator = ':';
                         size_t indexOfSeperator = str.find_first_of( seperator );
                         if ( indexOfSeperator == std::string::npos ) {
                                 seperator = ';';
                                 timeCode.DropFrame();
                                 indexOfSeperator = str.find_first_of( seperator );
                         } else {
                                 timeCode.IsNonDropFrame();
                         }
                         //assert( indexOfSeperator == 1 || indexOfSeperator == 2 );
                         str.assign( smpteTimeCode, indexOfSeperator );
                         timeCode.Hours( atoi( str.c_str() ) );
                         smpteTimeCode = smpteTimeCode + indexOfSeperator + 1;
                         str.assign( smpteTimeCode );
                         indexOfSeperator = str.find_first_of( seperator );
                         //assert( indexOfSeperator == 1 || indexOfSeperator == 2 );
                         str.assign( smpteTimeCode, indexOfSeperator );
                         timeCode.Minutes( atoi( str.c_str() ) );
                         smpteTimeCode = smpteTimeCode + indexOfSeperator + 1;
                         str.assign( smpteTimeCode );
                         indexOfSeperator = str.find_first_of( seperator );
                         //assert( indexOfSeperator == 1 || indexOfSeperator == 2 );
                         str.assign( smpteTimeCode, indexOfSeperator );
                         timeCode.Seconds( atoi( str.c_str() ) );
                         str.assign( smpteTimeCode + indexOfSeperator + 1 );
                         timeCode.Frames( atoi( str.c_str() ) );
                 }
         }
Variable Documentation
const EditUnitDuration UMC::kEditUnitDurationTillEnd = Max_UMC_Uns64 static
Definition at line 104 of file UMCDefines.h.
const EditUnitInCount UMC::kEditUnitInCountFromBeginning = 0 static
Definition at line 103 of file UMCDefines.h.
const std::string UMC::kEmptyString
const UMC_Int16 UMC::Max_UMC_Int16 = ((UMC_Int16) 0x7FFF) static
Definition at line 94 of file UMCDefines.h.
const UMC_Int32 UMC::Max_UMC_Int32 = ((UMC_Int32) 0x7FFFFFFF) static
Definition at line 96 of file UMCDefines.h.
const UMC_Int64 UMC::Max_UMC_Int64 = ((UMC_Int64) 0x7FFFFFFFFFFFFFFFLL) static
Definition at line 98 of file UMCDefines.h.
const UMC_Int8 UMC::Max_UMC_Int8 = ((UMC_Int8) 0x7F) static
Definition at line 92 of file UMCDefines.h.
const UMC_Uns16 UMC::Max_UMC_Uns16 = ((UMC_Uns16) 0xFFFF) static
Definition at line 85 of file UMCDefines.h.
const UMC_Uns32 UMC::Max_UMC_Uns32 = ((UMC_Uns32) 0xFFFFFFFF) static
Definition at line 87 of file UMCDefines.h.
const UMC_Uns64 UMC::Max_UMC_Uns64 = ((UMC_Uns64) 0xFFFFFFFFFFFFFFFFLL) static
Definition at line 89 of file UMCDefines.h.
const UMC_Uns8 UMC::Max_UMC_Uns8 = ((UMC_Uns8) 0xFF) static
Definition at line 83 of file UMCDefines.h.
const UMC_Int16 UMC::Min_UMC_Int16 = ((UMC_Int16) 0x8000) static
Definition at line 93 of file UMCDefines.h.
const UMC_Int32 UMC::Min_UMC_Int32 = ((UMC_Int32) 0x80000000) static
Definition at line 95 of file UMCDefines.h.
const UMC_Int64 UMC::Min_UMC_Int64 = ((UMC_Int64) 0x8000000000000000LL) static
Definition at line 97 of file UMCDefines.h.
const UMC_Int8 UMC::Min_UMC_Int8 = ((UMC_Int8) 0x80) static
Definition at line 91 of file UMCDefines.h.
const UMC_Uns16 UMC::Min_UMC_Uns16 = ((UMC_Uns16) 0x00) static
Definition at line 84 of file UMCDefines.h.
const UMC_Uns32 UMC::Min_UMC_Uns32 = ((UMC_Uns32) 0x00) static
Definition at line 86 of file UMCDefines.h.
const UMC_Uns64 UMC::Min_UMC_Uns64 = ((UMC_Uns64) 0x00) static
Definition at line 88 of file UMCDefines.h.
const UMC_Uns8 UMC::Min_UMC_Uns8 = ((UMC_Uns8) 0x00) static
Definition at line 82 of file UMCDefines.h.
const size_t UMC::npos = std::string::npos static
Definition at line 106 of file UMCDefines.h.
Referenced by ParseSMPTETimeCode().